### ISSUE TITLE
About "Images in Language Space: Exploring the Suitability of Large Language Models for Vision & Language Tasks"

### ISSUE THREAD

**Issue by YuanLi95** [clp-research/language-models-multimodal-tasks#1]
Dear Dr. Sir,

My name is Li Yuan , and I am a P.h.D student at South China University of Technology. I have recently read some of your articles on ACL regarding "Images in Language Space: Exploring the Suitability of Large Language Models for Vision & Language Tasks."

If it is not too much trouble, could you please provide me with the corresponding code? If we decide to use your work in our project, we will be sure to properly cite your work. Thank you very much for your help.

Best regards,

Li Yuan, SCUT

**Comment by sherzod-hakimov** [comment]
Dear Yuan Li,

Thanks for your interest in our work. We are at the stage of putting the code together to share it. 

Is there any specific part that your interested in (so that I can prioritize accordingly) ?

Best,
Sherzod

**Comment by YuanLi95** [comment]
> 
Thanks Sherzod
I am very interested in the implementation of Extracting Image-as-Text-Representations, and it will bring inspiration to my work. Also please contact me at ynuyuanli@gmail.com

Baes,
Li Yuan

**Comment by sherzod-hakimov** [comment]
alright, I'll post the code within today.
